### PR TITLE
Upgrade to Unity 2020.3.21

### PR DESCRIPTION
**Pull request by ekolve**
This PR upgrades the project to Unity 2020.3.21.  The two reasons for this are 1. This updates us to the latest LTS version (also giving us support for C# 8).  2. This aligns the Unity version for the CloudRendering platform with the other two platforms we support (MacOS and Linux w/Xorg).

### CODE REVIEW

**Review by winthos — APPROVED** [review]
lgtm

**Review by mattdeitke — APPROVED** [review]
LGTM :)

**Comment by elimvb** [comment]
Looks great!

**Comment by ekolve** [comment]
I am postponing merging this into to main due to a bug with the CloudRendering engine associated with this version of Unity that they are currently in the process of fixing.

**Comment by ekolve** [comment]
Closing this request as the CloudRendering branch will bring in 2020.3.25 instead.

**Pull request closed without merging**
