### PR TITLE
add `Controller.fullscreen` for fullscreen/windowed option

### PR DESCRIPTION
**Pull request by valtron**

### CODE REVIEW

**Comment by ekolve** [comment]
Thanks for the PR. I'll test this out and merge. Are you creating custom builds for Windows to run ai2thor?

**Comment by valtron** [comment]
Yes.

**Comment by ekolve** [comment]
K. I'll will look at adding Windows to the build script so that Windows users can skip creating custom builds.

**Comment by ekolve** [comment]
i added the fullscreen option in a slightly different way - your code should continue to work. My method just passes the parameter whether its True or False so there isn't an assumption about what the default is for the player.

**Pull request closed without merging**
