### PR TITLE
Enables restoring a state to a previous metadata dump

### PR DESCRIPTION
**Pull request by danielgordon10**
Example
```python
env = ai2thor.controller.Controller()
env.start()

object_poses = [{"objectName": "Alarm_Clock_19", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.8197357, "x": 2.45610785, "z": 0.054755792}}, {"objectName": "Box_19", "rotation": {"y": 29.0781651, "x": 0.0, "z": 0.0}, "position": {"y": 0.2277, "x": 0.2524, "z": -2.042}}, {"objectName": "Book_19", "rotation": {"y": 0.0, "x": 0.0, "z": 0.0}, "position": {"y": 0.7308113, "x": 0.3694262, "z": 1.497829}}, {"objectName": "Waving_Statue_2", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.825887859, "x": 2.45610952, "z": 0.623093963}}, {"objectName": "Cellphone_1", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.9018043, "x": 2.45610833, "z": 0.244201869}}, {"objectName": "pillow_19 (1)", "rotation": {"y": 0.0, "x": 0.0, "z": 0.0}, "position": {"y": 0.809355736, "x": -0.0165137351, "z": 0.9677471}}, {"objectName": "pillow_19", "rotation": {"y": 0.0, "x": 0.0, "z": 0.0}, "position": {"y": 0.809355736, "x": -0.5954236, "z": 0.17262423}}, {"objectName": "Basketball_1", "rotation": {"y": 0.0, "x": 0.0, "z": 0.0}, "position": {"y": 0.121002644, "x": -1.231, "z": -0.18}}, {"objectName": "CreditCard_1", "rotation": {"y": 0.0, "x": 0.0, "z": 0.0}, "position": {"y": 0.9652092, "x": -0.5970831, "z": -1.69612169}}, {"objectName": "Keychain_1", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.820835769, "x": 2.64169884, "z": 0.6230935}}, {"objectName": "Pencil_4", "rotation": {"y": 270.000153, "x": -2.44993025e-05, "z": 0.207566246}, "position": {"y": 0.819101155, "x": 2.76542521, "z": 0.8125222}}, {"objectName": "Alarm_Clock_19", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.8197357, "x": 2.64169645, "z": -0.134690791}}, {"objectName": "Laptop_19", "rotation": {"y": 0.0, "x": 0.0, "z": 0.0}, "position": {"y": 0.7290222, "x": 0.1764562, "z": 0.437665224}}, {"objectName": "CD_1", "rotation": {"y": 0.0, "x": 0.0, "z": 0.0}, "position": {"y": 0.19092539, "x": 2.554471, "z": 0.0460591}}, {"objectName": "Pen_1", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.827185452, "x": 2.64169836, "z": 0.433647454}}]

env.reset('FloorPlan216_physics')
env.step({'action': 'Initialize', 'gridSize': 0.0625})
env.step((dict(
        action='SetSceneState',
        objectPoses=object_poses,
        objectToggles=[{'objectType': 'DeskLamp', 'isOn': False}]
)))
```

### CODE REVIEW

**Comment by danielgordon10** [comment]
This should result in the scene configuration in this video. Note github won't let you upload an mp4 directly :(
[video.mp4.zip](https://github.com/allenai/ai2thor/files/3283698/video.mp4.zip)

**Comment by ekolve** [comment]
Could you take a look at the changes I requested as well as resolve the conflicts?

**Comment by roozbehm** [comment]
How does this work for shattered objects?

**Comment by danielgordon10** [comment]
It probably doesn't. But this is more to make sure random initialize is less dependent on the seed than to restore an exact state. Maybe dealing with shattered/sliced/etc can come later?

**Comment by roozbehm** [comment]
It might be better not to merge this until restoring state changes are implemented since it causes inconsistencies.

**Comment by danielgordon10** [comment]
I renamed the functions and split them into two separate functions for pose/toggle. I think this should be good to merge into master now.

**Comment by danielgordon10** [comment]
I just found a bug with this. It doesn't remove things from `receptacleObjectIds` but it does add the new ones. It seems to hang onto objects that don't even exist anymore. For example
1. I initialize a scene 1 with `DishSponge|-01.94|+00.75|-01.71` in the sink
2. I restore a scene where the sponge is in the garbage can
3. Now DishSponge is called `DishSponge|-01.94|+00.05|+01.93`
4. The Sink's `receptacleObjectIds` still has `DishSponge|-01.94|+00.75|-01.71` (which doesn't exist anymore).
5. The garbage can's `receptacleObjectIds` has the new `DishSponge|-01.94|+00.05|+01.93`
6. `DishSponge|-01.94|+00.05|+01.93`'s `parentReceptacle` is empty, but `parentReceptacles` is BOTH the garbage can and the sink????

**Comment by winthos** [comment]
I'm re-posting this from the slack thread for visibility:

To fix this, instead of just adding `c.CurrentlyContainedObjects().Clear()` in the `GatherAllReceptaclesInScene()` function, also toggle the enabled state of the Collider to make sure the Contained objects are updated correctly. It should look like this:

```                 
c.CurrentlyContainedObjects().Clear();
c.GetComponent<Collider>().enabled = false;
c.GetComponent<Collider>().enabled = true;
```

**Comment by danielgordon10** [comment]
It looks like you already pulled in some of the changes to WIPFeatures.

**Pull request merged**
